config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books

  root "static#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	# belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :books
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = current_user.books
  end

  def show
    @book = current_user.books.find(params[:id])
  end

  def new
    @book = current_user.books.new
  end

  def create

    new_book = current_user.books.create(book_params)
    new_book.save

    redirect_to new_book

  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def update

    book = current_user.books.find(params[:id])
    book.update(book_params)

    redirect_to book
  end

  def destroy
    current_user.books.destroy(params[:id])
    redirect_to books_url
  end

  protected
  def book_params
    params.require(:book).permit(:title, :author, :img_url)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home
		@books = Book.all
       render template: "books/index"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="book">
  <p>Title: <strong><%= book.title %></strong></p>
  <p>Author: <strong><%= book.author %></strong></p>

  <%= image_tag book.img_url %>
  <br>
  <%= link_to "Show Page", book unless action_name == "show" %> 
  <%= link_to "Edit Page", edit_book_path(book) %>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit %>


<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form" %>

app/views/books/index.html.erb
<h1>All Books</h1>

<%= link_to "New Book", new_book_path %>

<br>

<%= render @books %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1>Book Show Page</h1>

  <%= render @book %>

<br>


<%= link_to "Destroy", @book, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookKeeperApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<p class="navbar-text pull-right">
		<% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</p>

	<% if notice %>
    	<p class="alert alert-success"><%= notice %></p>
  	<% end %>

  	<% if alert %>
    	<p class="alert alert-danger"><%= alert %></p>
  	<% end %>

    <%= yield %>
  </body>
</html>